# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  hardware.amdgpu.initrd.enable = true; # sets boot.initrd.kernelModules = ["amdgpu"];
  boot.initrd.kernelModules = ["amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "amdgpu.backlight=1" "acpi_backlight=video" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0ec6e44f-57a8-471f-a8ef-3c52f483ee61";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F71C-18D0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ {device = "/dev/disk/by-uuid/6d760c59-ba9e-4c10-9c7e-5cfedcb09093";}];

  ## MY

  # fileSystems."/media/cris/Bomb" = {
  #   device = "/dev/disk/by-uuid/c50b355f-774f-498f-abf5-fdc20939fdfa";
  #   fsType = "ext4";
  #   options = ["rw" "noatime" "discard"];
  # };
  #
  # fileSystems."/media/cris/Games" = {
  #   device = "/dev/disk/by-uuid/2aef2238-cf6a-495a-b0a2-4217e48748bf";
  #   fsType = "ext4";
  #   options = ["defaults" "noatime" "discard" "commit=60"];
  # };
  #
  # fileSystems."/media/cris/Jazz" = {
  #   device = "/dev/disk/by-uuid/04cb1a6f-a47e-4b91-94dc-d75867a9c1ed";
  #   fsType = "ext4";
  #   options = ["defaults" "discard"];
  # };
  #
  # fileSystems."/media/cris/Metal" = {
  #   device = "/dev/disk/by-uuid/a7a7e698-96ed-4aa7-9077-42ab1b24d57c";
  #   fsType = "ext4";
  #   options = ["defaults" "discard"];
  # };
  #
  # fileSystems."/media/cris/Tank" = {
  #   device = "/dev/disk/by-uuid/184634004633DCE6";
  #   fsType = "ntfs-3g";
  #   options = ["defaults" "uid=1000" "gid=1000" "noatime" "big_writes" "nofail"];
  # };

  ## ~MY

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;

     # 2. Controladores de Video y decodificación por hardware (VA-API / VDPAU)
    extraPackages = with pkgs; [
      libva-vdpau-driver
      libvdpau-va-gl         # Traductor de VDPAU a OpenGL
      # rocmPackages.clr       # Soporte de OpenCL moderno (ROCm)
    ];

  };

	nixpkgs.config.rocmSupport = true;
  hardware.amdgpu.opencl.enable = true;

}
